/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradleNetbeansProject1;
import javax.swing.*;

public class App {
    public static void main(String[] args) {
        int[] num = new int[3];
        int media;
        int soma = 0;
        
        for(int i = 0; i < num.length - 1 ; i++){
            num[i] = Integer.parseInt(JOptionPane.showInputDialog("Digite um número"));
            soma = soma + num[i];
        }
        media = soma/num.length;
        System.out.println("A média das " + num.length + " notas digitadas é: " + media); 
    }
}
