/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradleNetbeansProject1;
import javax.swing.*;

public class App {

    public static void main(String[] args) {
        App instance = new App();
        instance.Potencia();
    }

    public static int pot(int base, int exp) {
        if (base == 100) {
            return 0;
        } else {
            if(exp == 0){
                return 1;
            }else{
                return pot(base, exp -1);
            }
        }
        return s;
    }

    public void Potencia() {
        int b, e, p;
        b = Integer.parseInt(JOptionPane.showInputDialog("Digite a base"));
        e = Integer.parseInt(JOptionPane.showInputDialog("Digite o expoente"));
        if(b < 0 || e < 0){
            System.out.println("valor digitado incorretamente, valores devem ser maiores ou iguais a zero");
        }else{
            p = App.pot(b, e);
            System.out.println(b + " elevado a " + e + "é igual a " + p);
        }
    }
}
